Repository ASFHyP3/sentinel1-orbits-py, pull requests merged in 2024-08, with the labels that each got.

#3 Add CI/CD and packaging files
  .github/workflows/changelog.yml
  .github/workflows/create-jira-issue.yml
  .github/workflows/distribute.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release-template-comment.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tag-version.yml
  .github/workflows/test.yml
  MANIFEST.in
  environment.yml
  pyproject.toml
Labels: bumpless

#7 add comment for creating v0.0.0 tag
  .github/workflows/tag-version.yml
Labels: bumpless

#6 Release v0.1.0
  .github/CODEOWNERS
  .github/dependabot.yml
  .github/workflows/changelog.yml
  .github/workflows/create-jira-issue.yml
  .github/workflows/distribute.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release-template-comment.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tag-version.yml
  .github/workflows/test.yml
  CHANGELOG.md
  MANIFEST.in
  README.md
  environment.yml
  pyproject.toml
  src/s1_orbits/__init__.py
  src/s1_orbits/exceptions.py
  src/s1_orbits/s1_orbits.py
  tests/test_s1_orbits.py
Labels: minor

#9 Updated Usage Info and Docstring
  CHANGELOG.md
  README.md
  src/s1_orbits/s1_orbits.py
Labels: patch

#10 Release v0.1.1
  CHANGELOG.md
  README.md
  src/s1_orbits/s1_orbits.py
Labels: patch
